### ISSUE TITLE
test

### ISSUE THREAD

**Issue by bz404** [bianbian9388/blog#1]
aaa

**Comment by bbian9388** [comment]
> #######- - - - - - - **- - - _[djdjdjdjdjdjdjdjdjdjdjdjjdd]()_[]()[[[[@````**_[[[[]()]()]()]()_**````]()]()]()]()**图
> 
>       冠状病毒性肺炎克星Remdesivir的合成
> 
> 化学结构：
> 
> 
> 化学名：(2S)-2-ethylbutyl2-(((S)-(((2R,3S,4R,5R)-5-(4-aminopyrrolo[2,1f][1,2,4]triazin-7-yl)-5-cyano-3,4-dihydroxytetrahydrofuran-2-yl)methoxy)(phenoxy)  phosphoryl)amino)propanoate
> 
> CAS号：1809249-37-3
> 化合物性质（预测）
> 
> 合成路线图：
> 
> 该路线为Nature2016年报道的第二代合成方法，实验室可放大至百克级。共6步反应，收率分别为40%，85%，86%，90%，70%，69%，中间体6合成需要两步，收率分别80%，39%。
> 
> 图源：
> 
> 所需原料清单：
> 
> 化合物1，可直接购买，CAS：55094-52-5；
> 
> 化合物2，需要合成，原料CAS：159326-68-8，合成方法如下：
> 
> 
> 化合物9，需要合成，所需原料化合物8（cas：946511-97-3），4-硝基苯酚（cas：100-02-7），二氯化磷酸苯酯（cas：770-12-7）
> 
> 
> 
> 其它原料：
> 
> TMSCl，CAS: 75-77-4 
> PhMgCl 苯基氯化镁 cas：100-59-4
> 异丙基氯化镁-氯化锂 CAS：745038-86-2
> 三甲基腈硅烷(TMSCN) CAS 号:7677-24-9 
> 三氟甲磺酸（TfOH）cas：1493-13-6
> 硅基三氟甲磺酸(TMSOTf) CAS:88188-06-1
> 三氯化硼(BCl3) CAS: 10294-34-5
> 2,2-二甲氧基丙烷 CAS: 77-76-9
> 三乙胺 CAS: 121-44-8
> N,N-二异丙基乙胺 CAS: 7087-68-5
> 
> 化合物3的制备
> 
> 
> 图源：Nature

红花岗区事情

**Comment by bbian9388** [comment]
广告公司

**Comment by bz404** [comment]
可口可乐了
